# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wudi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import QPixmap, QPainter, QCursor, QBitmap
from PyQt5.QtCore import Qt, QSize, QTimer
from PyQt5.QtWidgets import (QDialog, QVBoxLayout, QWidget,
                            QPushButton, QGridLayout, QSpacerItem,
                            QSizePolicy, QLabel, QApplication)
from PyQt5.QtCore import Qt

#from frameless import Ui_Dialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 630)
        MainWindow.setFixedSize(1120,630)
        MainWindow.layout=QtWidgets.QGridLayout()
        MainWindow.layout.setContentsMargins(0, 0, 0, 0)
        MainWindow.setObjectName('body')
        MainWindow.setStyleSheet('''
                   QMainWindow#body{
                       background-color:none;

                   }
                   QToolButton,QPushButton{
                       border:none;
                   }
                   QPushButton:hover{
                       color:#333;
                   }
                   QCheckBox::indicator {
                       border: 1px solid #9FA3A9;

                   }
                   QWidget#acount_group,#pwd_gourp{
                       border-bottom:1px solid #E0E0E0;
                   }
                   QCheckBox,QLabel,QRadioButton,QTextEdit{
                       color:white;
                   }
                   
                   QToolButton#wx_icon{
                       color:#9FA3A9;
                   }
                   QToolButton#wx_icon:hover{
                       color:#1ABB0E;
                   }

                   QToolButton#qq_icon{
                       color:#378AFE;
                   }
                   QToolButton#qq_icon:hover{
                       color:#378AFE;
                   }
                   '''
                           )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
       # self.label_55=QLabel()self.movie=QtGui.Qmovie("./aaaa.gif")#url('./closeb_hover.svg')self.label_55.QtGui.Qmovie(self.movie)self.movie.start()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label.setObjectName("label")

        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(27, 25, 54, 12))
        self.label_29.setObjectName("label_29")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(540, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(727, 25, 54, 12))
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(297, 25, 54, 12))
        self.label_21.setObjectName("label_21")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(297, 163, 351, 311))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.setStyleSheet("QTextEdit\n"
                                      "{\n"
                                      "\n"
                                      "background:rgba(255,0,0,0);\n"
                                      "border:2px solid rgba(255,255,255,0.65);\n"
                                      "}")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(820, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(750, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(610, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(27, 416, 54, 12))
        self.label_26.setObjectName("label_26")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(143, 416, 54, 12))
        self.label_31.setObjectName("label_31")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(727, 43, 351, 431))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_4.setStyleSheet("QTextEdit\n"
                                      "{\n"
                                      "\n"
                                      "background:rgba(255,0,0,0);\n"
                                      "border:2px solid rgba(255,255,255,0.65);\n"
                                      "}")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(890, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_18.setObjectName("label_18")
        # self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setGeometry(QtCore.QRect(0, 0, 1106, 630))
        # self.label_3.setStyleSheet('''"QLabel\n"
# "{\n"
# "background:white;\n"
#                           "background-image:url(./bigman.jpg)"
# "}"''')
#         self.label_3.setText("")
#         self.label_3.setObjectName("label_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(680, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_15.setObjectName("label_15")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(297, 43, 351, 91))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setStyleSheet("QTextEdit\n"
"{\n"
"\n"
"background:rgba(255,0,0,0);\n"
"border:2px solid rgba(255,255,255,0.65);\n"
"}")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(8, 573, 1081, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit\n"
"{\n"
"\n"
"background:rgba(255,0,0,0);\n"
"border:0px;\n"
"}")
        #self.textEdit_2.setTextColor(self,"white")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(27, 303, 221, 111))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"background:none;\n"
"border:2px solid rgba(255,255,255,0.65);\n"
"}")

        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.setWindowOpacity(0.8)  # 设置窗口透明度

        #self.label_4.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 设置窗口背景透明
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(13, 516, 1088, 55))
        self.label_5.setStyleSheet("image: url('./kuang.png');")
        self.label_5.setText("")
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1074, 3, 31, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setStyleSheet('''
        QPushButton#pushButton_7{border-image:url('./closeb.svg');}
        QPushButton#pushButton_7:hover{border-image:url('./closeb_hover.svg');}
        ''')

        self.pushButton_7.setToolTip("关闭")
        self.pushButton_7.clicked.connect(self.close_btn_slot)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(27, 433, 101, 41))
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"background:none;\n"
"border:2px solid rgba(255,255,255,0.65)"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(143, 433, 101, 41))
        self.label_30.setStyleSheet("QLabel\n"
                                   "{\n"
                                   "background:none;\n"
                                   "border:2px solid rgba(255,255,255,0.65)"
                                   "}")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(27, 213, 221, 71))
        self.label_23.setStyleSheet("QLabel\n"
"{\n"
"background:none;\n"
"border:2px solid rgba(255,255,255,0.65);\n"
"}")
        self.label_23.setObjectName("label_23")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(27, 145, 54, 12))
        self.label_28.setObjectName("label_28")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(960, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_19.setObjectName("label_19")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(400, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(297, 145, 54, 12))
        self.label_24.setObjectName("label_24")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(27, 43, 221, 91))
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"background:none;\n"
"border:2px solid rgba(255,255,255,0.65);\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(27, 196, 54, 12))
        self.label_27.setObjectName("label_27")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(27, 163, 91, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setStyleSheet("QTextEdit\n"
                                      "{\n"
                                      "\n"
                                      "background:rgba(255,0,0,0);\n"
                                      "border:2px solid rgba(255,255,255,0.65);\n"
                                      "}")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(470, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(330, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1030, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(28, 287, 54, 12))
        self.label_25.setObjectName("label_25")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 520, 34, 47))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(203, 203, 203);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(40, 80, 89, 16))
        self.radioButton.setObjectName("radioButton")


        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 80, 89, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 315, 75, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet('''
                                QPushButton#pushButton{border-image:url('./bgray.svg');}
                                QPushButton#pushButton:hover{border-image:url('./bgreen.svg');};
                                color:white
                                ''')

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 315, 75, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet('''
                                QPushButton#pushButton_2{border-image:url('./bgray.svg');}
                                QPushButton#pushButton_2:hover{border-image:url('./bblue.svg');};
                                color:white
                                ''')
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 355, 75, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet('''
                                QPushButton#pushButton_3{border-image:url('./bgray.svg');}
                                QPushButton#pushButton_3:hover{border-image:url('./byellow.svg');};
                                color:white;
                                
                                ''')
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 355, 75, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet('''
                                QPushButton#pushButton_4{border-image:url('./bgray.svg');}
                                QPushButton#pushButton_4:hover{border-image:url('./bred.svg');};
                                color:white
                                ''')
        # self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_6.setGeometry(QtCore.QRect(1036, 3, 31, 31))
        # self.pushButton_6.setObjectName("pushButton_6")
        # self.pushButton_6.setStyleSheet('''
        #         QPushButton#pushButton_6{border-image:url('./minus.svg');}
        #         QPushButton#pushButton_6:hover{border-image:url('./minus_hover.svg');}
        #         ''')
        # self.pushButton_6.setToolTip("最小化")
        # self.pushButton_6.clicked.connect(self.setMinButtons)
        # self.pushButton_6.setWindowFlags(Qt.WindowCloseButtonHint)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(43, 442, 71, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(131, 158, 51, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet('''
                        QPushButton#pushButton_5{border-image:url('./bgray.svg');}
                        QPushButton#pushButton_5:hover{border-image:url('./bgreen.svg');};
                        color:white
                        ''')

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(193, 158, 51, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setStyleSheet('''
                                QPushButton#pushButton_8{border-image:url('./bgray.svg');}
                                QPushButton#pushButton_8:hover{border-image:url('./bred.svg');};
                                color:white
                                ''')
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(156, 434, 75, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setStyleSheet('''
                                        QPushButton#pushButton_9{border-image:url('./bgray.svg');}
                                        QPushButton#pushButton_9:hover{border-image:url('./bred.svg');};
                                        color:white
                                        ''')
        # self.label_3.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_29.raise_()
        self.label_13.raise_()
        self.label_22.raise_()
        self.label_21.raise_()
        self.textEdit_5.raise_()
        self.label_9.raise_()
        self.label_17.raise_()
        self.label_16.raise_()
        self.label_14.raise_()
        self.label_26.raise_()
        self.label_31.raise_()

        self.textEdit_4.raise_()
        self.label_18.raise_()
        self.label_15.raise_()
        self.textEdit_3.raise_()
        self.textEdit_2.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.pushButton_7.raise_()
        self.label_6.raise_()
        self.label_30.raise_()
        self.label_23.raise_()
        self.label_28.raise_()
        self.label_19.raise_()
        self.label_11.raise_()
        self.label_24.raise_()
        self.label_7.raise_()
        self.label_27.raise_()
        self.textEdit.raise_()
        self.label_12.raise_()
        self.label_10.raise_()
        self.label_20.raise_()
        self.label_25.raise_()
        self.label_2.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        # self.pushButton_6.raise_()
        self.checkBox.raise_()
        self.pushButton_5.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 窗口关闭信号

    def close_btn_slot(self):
        # self.close()
        self.parent().close()

    def setMinButtons(self):

      #  if bool == True:

            self.pushButton_6.clicked.connect(self.showMinimized)  # 按钮信号连接到最小化窗口的槽函数


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "输入选择"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "运行结果"))
        self.label_21.setText(_translate("MainWindow", "提示框"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "动态演示"))
        self.label_31.setText(_translate("MainWindow", "清除列表"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            ↑</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_7.setText(_translate("MainWindow", ""))
        self.label_23.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">若选择系统生成，请输入磁道数</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">若选择手动输入，请输入磁道号</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "输入框"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "磁盘调度"))
        self.label_27.setText(_translate("MainWindow", "输入提示"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "算法选择"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton.setText(_translate("MainWindow", "系统生成"))
        self.radioButton_2.setText(_translate("MainWindow", "手动输入"))
        self.pushButton.setText(_translate("MainWindow", "FCFS"))
        self.pushButton_2.setText(_translate("MainWindow", "SSTF"))
        self.pushButton_3.setText(_translate("MainWindow", "SCAN"))
        self.pushButton_4.setText(_translate("MainWindow", "CSCAN"))
        # self.pushButton_6.setText(_translate("MainWindow", ""))
        self.checkBox.setText(_translate("MainWindow", "动态演示"))
        self.pushButton_5.setText(_translate("MainWindow", "增添"))
        self.pushButton_8.setText(_translate("MainWindow", "删除"))
        self.pushButton_9.setText(_translate("MainWindow", "清除"))

class Container(QtWidgets.QWidget):
    def __init__(self, window):
        super().__init__()
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        lay = QtWidgets.QVBoxLayout(self)
        lay.addWidget(window)
        lay.setContentsMargins(10, 10, 10, 10)
        shadow = QtWidgets.QGraphicsDropShadowEffect(self,
                                                                 blurRadius=9.0,
                                                                 color=QtGui.QColor(116, 116, 116),
                                                                 offset=QtCore.QPointF(0, 0)
                                                                 )

        window.setGraphicsEffect(shadow)

    def mousePressEvent(self, event):  # 鼠标长按事件
        if event.button() == QtCore.Qt.LeftButton:
            self.m_drag = True
            self.m_DragPosition = event.globalPos() - self.pos()
            event.accept()
            self.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))

    def mouseMoveEvent(self, QMouseEvent):  # 鼠标移动事件
        if QtCore.Qt.LeftButton and self.m_drag:
            self.move(QMouseEvent.globalPos() - self.m_DragPosition)
            QMouseEvent.accept()

    def mouseReleaseEvent(self, QMouseEvent):  # 鼠标释放事件
        self.m_drag = False
        self.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

#import ioio_rc
class AMainWindow(QWidget):
    BorderColor     = QtGui.QColor(0, 0, 0, 255)
    BackgroundColor = QtGui.QColor(255, 165, 0, 180)

    def __init__(self, window):
        super().__init__()
        self.setWindowFlags(Qt.FramelessWindowHint)
        self.setAttribute(Qt.WA_TranslucentBackground, True)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Size = QWidget.setFixedSize(self, 1141, 647)
        lay = QtWidgets.QVBoxLayout(self)
        lay.addWidget(window)
        lay.setContentsMargins(10, 10, 10, 10)
        shadow = QtWidgets.QGraphicsDropShadowEffect(self,
                                                     blurRadius=9.0,
                                                     color=QtGui.QColor(116, 116, 116),
                                                     offset=QtCore.QPointF(0, 0)
                                                     )

        window.setGraphicsEffect(shadow)
        self.initUI()  # 界面绘制交给InitUi方法

    def initUI(self):
        pix = QPixmap('bigone.jpg')

        lb1 = QLabel(self)
        lb1.setGeometry(0, 0, 1141, 647)
        lb1.setStyleSheet("background-color:rgba(255,0,0,30)")
        lb1.setPixmap(pix)
        lb1.setScaledContents(True)
        print(lb1.size())
        lb1.lower()
        # 设置窗口的位置和大小
        #self.setGeometry(300, 300, 600, 600)
        # 设置窗口的标题
      #  self.setWindowTitle('Example')

        # 显示窗口
     #   self.show()





    def mousePressEvent(self, event):  # 鼠标长按事件
            if event.button() == QtCore.Qt.LeftButton:
                    self.m_drag = True
                    self.m_DragPosition = event.globalPos() - self.pos()
                    event.accept()
                    self.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))

    def mouseMoveEvent(self, QMouseEvent):  # 鼠标移动事件
            if QtCore.Qt.LeftButton and self.m_drag:
                    self.move(QMouseEvent.globalPos() - self.m_DragPosition)
                    QMouseEvent.accept()

    def mouseReleaseEvent(self, QMouseEvent):  # 鼠标释放事件
            self.m_drag = False
            self.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

    # def paintEvent(self, event):
    #     super(AMainWindow, self).paintEvent(event)
    #
    #     painter = QPainter(self)
    #     painter.setRenderHint(QPainter.Antialiasing)
    #
    #     rectPath = QtGui.QPainterPath()
    #     height = self.height()
    #     rectPath.addRoundedRect(QtCore.QRectF(2, 2, self.width()-4, height), 15, 15)
    #     painter.setPen(QtGui.QPen(self.BorderColor, 2, Qt.SolidLine,
    #                              Qt.RoundCap, Qt.RoundJoin))
    #     painter.setBrush(self.BackgroundColor)
    #     painter.drawPath(rectPath)
    #     painter.setPen(QtGui.QPen(self.BackgroundColor, 2,
    #                              Qt.SolidLine, Qt.RoundCap, Qt.RoundJoin))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()

    ui = Ui_MainWindow()  # 根据上面所创建的类的名字更改

    ui.setupUi(MainWindow)
    MainWindow=AMainWindow(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())


