# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zy.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, WindowMain):
        WindowMain.setObjectName("WindowMain")
        WindowMain.setWindowModality(QtCore.Qt.ApplicationModal)
        WindowMain.resize(1120, 630)
        WindowMain.setAcceptDrops(False)
        WindowMain.setToolTipDuration(1)
        WindowMain.setStyleSheet("")
        WindowMain.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(WindowMain)
        self.centralwidget.setObjectName("centralwidget")
        self.Tag = QtWidgets.QTabWidget(self.centralwidget)
        self.Tag.setGeometry(QtCore.QRect(0, 0, 1121, 641))
        self.Tag.setStyleSheet("QTabWidget::pane{border-width: 1px;border-color:white;border-style:outset;border-radius: 15px;background-color: rgb(116, 190, 255);background: transparent;}​\n"
"\n"
"QTabWidget::tab-bar{left:0px;}\n"
"\n"
"QTabBar::tab{width:160px;height:46px;font:20px;color:white;border-style:outset;border-radius: 5px;}\n"
"\n"
"QTabBar::tab:selected{margin-left: 1;margin-right: 0;background-color: rgb(255, 118, 106);}\n"
"\n"
"QTabBar::tab:!selected{margin-left: 1;margin-right: 0;background-color: rgb(245, 219, 159);}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:hover:!selected{color: white;margin-left: 1;margin-right: 0;}\n"
"\n"
"QTabBar::tab:!selected{margin-top: 6px;margin-bottom: -6px;}​")
        self.Tag.setObjectName("Tag")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 130, 585))
        self.label_7.setStyleSheet("QLabel{background-color:pink;border-radius:15px;}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setGeometry(QtCore.QRect(190, 10, 491, 211))
        self.label_8.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 171, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(210, 60, 211, 41))
        self.label_3.setObjectName("label_3")
        self.lineEdit_101 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_101.setGeometry(QtCore.QRect(420, 70, 241, 31))
        self.lineEdit_101.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_101.setText("")
        self.lineEdit_101.setObjectName("lineEdit_101")
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setGeometry(QtCore.QRect(210, 100, 201, 41))
        self.label_4.setObjectName("label_4")
        self.lineEdit_102 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_102.setGeometry(QtCore.QRect(420, 110, 241, 31))
        self.lineEdit_102.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.pushButton_101 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_101.setGeometry(QtCore.QRect(230, 150, 121, 41))
        self.pushButton_101.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"\n"
"}")
        self.pushButton_101.setObjectName("pushButton_101")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 150, 121, 41))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_100 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_100.setGeometry(QtCore.QRect(700, 50, 171, 231))
        self.textEdit_100.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_100.setObjectName("textEdit_100")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(700, 20, 161, 31))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setGeometry(QtCore.QRect(690, 10, 191, 291))
        self.label_10.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setGeometry(QtCore.QRect(890, 10, 201, 291))
        self.label_11.setStyleSheet("\n"
"QLabel{background-color:rgb(255, 196, 209,0.8);border-radius:15px;}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setGeometry(QtCore.QRect(900, 20, 181, 31))
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(190, 230, 491, 71))
        self.label.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}\n"
"")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 320, 31, 31))
        self.pushButton_4.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_5.setGeometry(QtCore.QRect(490, 320, 31, 31))
        self.pushButton_5.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 320, 31, 31))
        self.pushButton_3.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_6.setGeometry(QtCore.QRect(770, 320, 31, 31))
        self.pushButton_6.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_7.setGeometry(QtCore.QRect(910, 320, 31, 31))
        self.pushButton_7.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 320, 31, 31))
        self.pushButton_8.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setGeometry(QtCore.QRect(190, 360, 921, 211))
        self.label_9.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setGeometry(QtCore.QRect(200, 370, 181, 31))
        self.label_6.setObjectName("label_6")
        self.textEdit_1 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_1.setGeometry(QtCore.QRect(220, 400, 41, 161))
        self.textEdit_1.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_1.setObjectName("textEdit_1")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_2.setGeometry(QtCore.QRect(300, 400, 41, 161))
        self.textEdit_2.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_3.setGeometry(QtCore.QRect(380, 400, 41, 161))
        self.textEdit_3.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_4.setGeometry(QtCore.QRect(460, 400, 41, 161))
        self.textEdit_4.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_5.setGeometry(QtCore.QRect(540, 400, 41, 161))
        self.textEdit_5.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_6.setGeometry(QtCore.QRect(620, 400, 41, 161))
        self.textEdit_6.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_7.setGeometry(QtCore.QRect(700, 400, 41, 161))
        self.textEdit_7.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_8.setGeometry(QtCore.QRect(780, 400, 41, 161))
        self.textEdit_8.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_9.setGeometry(QtCore.QRect(860, 400, 41, 161))
        self.textEdit_9.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_10.setGeometry(QtCore.QRect(940, 400, 41, 161))
        self.textEdit_10.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_11.setGeometry(QtCore.QRect(1020, 400, 41, 161))
        self.textEdit_11.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_49 = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_49.setGeometry(QtCore.QRect(900, 50, 171, 231))
        self.textEdit_49.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)\n"
"")
        self.textEdit_49.setObjectName("textEdit_49")
        self.pushButton_37 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_37.setGeometry(QtCore.QRect(1050, 320, 31, 31))
        self.pushButton_37.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_37.setText("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(130, 0, 990, 585))
        self.frame.setStyleSheet("QFrame{background-image: url(:/pict/蓝色简约纹理.png);border-radius: 15px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.label_10.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_101.raise_()
        self.label_4.raise_()
        self.lineEdit_102.raise_()
        self.pushButton_101.raise_()
        self.pushButton_2.raise_()
        self.textEdit_100.raise_()
        self.label_5.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_3.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.label_9.raise_()
        self.label_6.raise_()
        self.textEdit_1.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.textEdit_5.raise_()
        self.textEdit_6.raise_()
        self.textEdit_7.raise_()
        self.textEdit_8.raise_()
        self.textEdit_9.raise_()
        self.textEdit_10.raise_()
        self.textEdit_11.raise_()
        self.textEdit_49.raise_()
        self.pushButton_37.raise_()
        self.Tag.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_205 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_205.setGeometry(QtCore.QRect(540, 400, 41, 161))
        self.textEdit_205.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_205.setObjectName("textEdit_205")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(910, 320, 31, 31))
        self.pushButton_17.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(210, 100, 201, 41))
        self.label_25.setObjectName("label_25")
        self.textEdit_202 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_202.setGeometry(QtCore.QRect(300, 400, 41, 161))
        self.textEdit_202.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_202.setObjectName("textEdit_202")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(690, 10, 191, 291))
        self.label_26.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(700, 20, 161, 31))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(200, 370, 181, 31))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(190, 10, 491, 211))
        self.label_29.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(890, 10, 201, 291))
        self.label_30.setStyleSheet("QLabel{background-color:rgb(255, 196, 209,0.8);border-radius:15px;}\n"
"")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(190, 230, 491, 71))
        self.label_31.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_31.setObjectName("label_31")
        self.lineEdit_202 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_202.setGeometry(QtCore.QRect(420, 110, 241, 31))
        self.lineEdit_202.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_202.setObjectName("lineEdit_202")
        self.textEdit_209 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_209.setGeometry(QtCore.QRect(860, 400, 41, 161))
        self.textEdit_209.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_209.setObjectName("textEdit_209")
        self.textEdit_201 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_201.setGeometry(QtCore.QRect(220, 400, 41, 161))
        self.textEdit_201.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_201.setObjectName("textEdit_201")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(190, 360, 921, 211))
        self.label_32.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_32.setObjectName("label_32")
        self.lineEdit_201 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_201.setGeometry(QtCore.QRect(420, 70, 241, 31))
        self.lineEdit_201.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_201.setText("")
        self.lineEdit_201.setObjectName("lineEdit_201")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(490, 320, 31, 31))
        self.pushButton_18.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(900, 20, 181, 31))
        self.label_33.setObjectName("label_33")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_19.setGeometry(QtCore.QRect(440, 150, 121, 41))
        self.pushButton_19.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.textEdit_210 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_210.setGeometry(QtCore.QRect(940, 400, 41, 161))
        self.textEdit_210.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_210.setObjectName("textEdit_210")
        self.textEdit_207 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_207.setGeometry(QtCore.QRect(700, 400, 41, 161))
        self.textEdit_207.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_207.setObjectName("textEdit_207")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_20.setGeometry(QtCore.QRect(630, 320, 31, 31))
        self.pushButton_20.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.textEdit_211 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_211.setGeometry(QtCore.QRect(1020, 400, 41, 161))
        self.textEdit_211.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_211.setObjectName("textEdit_211")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(210, 20, 171, 41))
        self.label_34.setObjectName("label_34")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_21.setGeometry(QtCore.QRect(350, 320, 31, 31))
        self.pushButton_21.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(210, 60, 211, 41))
        self.label_35.setObjectName("label_35")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_22.setGeometry(QtCore.QRect(770, 320, 31, 31))
        self.pushButton_22.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.textEdit_200 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_200.setGeometry(QtCore.QRect(700, 50, 171, 231))
        self.textEdit_200.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_200.setObjectName("textEdit_200")
        self.pushButton_201 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_201.setGeometry(QtCore.QRect(230, 150, 121, 41))
        self.pushButton_201.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"\n"
"}\n"
"")
        self.pushButton_201.setObjectName("pushButton_201")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(10, 10, 131, 571))
        self.label_36.setStyleSheet("QLabel{background-color:pink;border-radius:15px;}\n"
"background-color: rgb(255, 103, 171);")
        self.label_36.setObjectName("label_36")
        self.textEdit_203 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_203.setGeometry(QtCore.QRect(380, 400, 41, 161))
        self.textEdit_203.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_203.setObjectName("textEdit_203")
        self.textEdit_204 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_204.setGeometry(QtCore.QRect(460, 400, 41, 161))
        self.textEdit_204.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_204.setObjectName("textEdit_204")
        self.textEdit_208 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_208.setGeometry(QtCore.QRect(780, 400, 41, 161))
        self.textEdit_208.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_208.setObjectName("textEdit_208")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_24.setGeometry(QtCore.QRect(210, 320, 31, 31))
        self.pushButton_24.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.textEdit_206 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_206.setGeometry(QtCore.QRect(620, 400, 41, 161))
        self.textEdit_206.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_206.setObjectName("textEdit_206")
        self.textEdit_50 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_50.setGeometry(QtCore.QRect(900, 50, 171, 231))
        self.textEdit_50.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_50.setObjectName("textEdit_50")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_23.setGeometry(QtCore.QRect(1050, 320, 31, 31))
        self.pushButton_23.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_32.raise_()
        self.label_29.raise_()
        self.textEdit_205.raise_()
        self.pushButton_17.raise_()
        self.label_25.raise_()
        self.textEdit_202.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.lineEdit_202.raise_()
        self.textEdit_209.raise_()
        self.textEdit_201.raise_()
        self.lineEdit_201.raise_()
        self.pushButton_18.raise_()
        self.label_33.raise_()
        self.pushButton_19.raise_()
        self.textEdit_210.raise_()
        self.textEdit_207.raise_()
        self.pushButton_20.raise_()
        self.textEdit_211.raise_()
        self.label_34.raise_()
        self.pushButton_21.raise_()
        self.label_35.raise_()
        self.pushButton_22.raise_()
        self.textEdit_200.raise_()
        self.pushButton_201.raise_()
        self.label_36.raise_()
        self.textEdit_203.raise_()
        self.textEdit_204.raise_()
        self.textEdit_208.raise_()
        self.pushButton_24.raise_()
        self.textEdit_206.raise_()
        self.textEdit_50.raise_()
        self.pushButton_23.raise_()
        self.Tag.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit_305 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_305.setGeometry(QtCore.QRect(540, 400, 41, 161))
        self.textEdit_305.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_305.setObjectName("textEdit_305")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(210, 100, 201, 41))
        self.label_13.setObjectName("label_13")
        self.textEdit_302 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_302.setGeometry(QtCore.QRect(300, 400, 41, 161))
        self.textEdit_302.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_302.setObjectName("textEdit_302")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(690, 10, 191, 291))
        self.label_14.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(700, 20, 161, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(200, 370, 181, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(190, 10, 491, 211))
        self.label_17.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(890, 10, 201, 291))
        self.label_18.setStyleSheet("QLabel{background-color: rgb(51, 180, 255,0.8);border-radius:15px;}\n"
"")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(190, 230, 491, 71))
        self.label_19.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_19.setObjectName("label_19")
        self.lineEdit_302 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_302.setGeometry(QtCore.QRect(420, 110, 241, 31))
        self.lineEdit_302.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_302.setObjectName("lineEdit_302")
        self.textEdit_309 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_309.setGeometry(QtCore.QRect(860, 400, 41, 161))
        self.textEdit_309.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_309.setObjectName("textEdit_309")
        self.textEdit_301 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_301.setGeometry(QtCore.QRect(220, 400, 41, 161))
        self.textEdit_301.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_301.setObjectName("textEdit_301")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(190, 360, 921, 211))
        self.label_20.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_20.setObjectName("label_20")
        self.lineEdit_301 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_301.setGeometry(QtCore.QRect(420, 70, 241, 31))
        self.lineEdit_301.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_301.setText("")
        self.lineEdit_301.setObjectName("lineEdit_301")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(900, 20, 181, 31))
        self.label_21.setObjectName("label_21")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(440, 150, 121, 41))
        self.pushButton_11.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.textEdit_310 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_310.setGeometry(QtCore.QRect(940, 400, 41, 161))
        self.textEdit_310.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_310.setObjectName("textEdit_310")
        self.textEdit_307 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_307.setGeometry(QtCore.QRect(700, 400, 41, 161))
        self.textEdit_307.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_307.setObjectName("textEdit_307")
        self.textEdit_311 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_311.setGeometry(QtCore.QRect(1020, 400, 41, 161))
        self.textEdit_311.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_311.setObjectName("textEdit_311")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(210, 20, 171, 41))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(210, 60, 211, 41))
        self.label_23.setObjectName("label_23")
        self.textEdit_300 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_300.setGeometry(QtCore.QRect(700, 50, 171, 231))
        self.textEdit_300.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_300.setObjectName("textEdit_300")
        self.pushButton_301 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_301.setGeometry(QtCore.QRect(230, 150, 121, 41))
        self.pushButton_301.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"\n"
"}\n"
"")
        self.pushButton_301.setObjectName("pushButton_301")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 131, 571))
        self.label_24.setStyleSheet("QLabel{background-color: rgb(51, 180, 255);border-radius:15px;}\n"
"")
        self.label_24.setObjectName("label_24")
        self.textEdit_303 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_303.setGeometry(QtCore.QRect(380, 400, 41, 161))
        self.textEdit_303.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_303.setObjectName("textEdit_303")
        self.textEdit_304 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_304.setGeometry(QtCore.QRect(460, 400, 41, 161))
        self.textEdit_304.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_304.setObjectName("textEdit_304")
        self.textEdit_308 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_308.setGeometry(QtCore.QRect(780, 400, 41, 161))
        self.textEdit_308.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_308.setObjectName("textEdit_308")
        self.textEdit_306 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_306.setGeometry(QtCore.QRect(620, 400, 41, 161))
        self.textEdit_306.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_306.setObjectName("textEdit_306")
        self.textEdit_51 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_51.setGeometry(QtCore.QRect(900, 50, 181, 231))
        self.textEdit_51.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_51.setObjectName("textEdit_51")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(1050, 320, 31, 31))
        self.pushButton_9.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_31.setGeometry(QtCore.QRect(630, 320, 31, 31))
        self.pushButton_31.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_27.setGeometry(QtCore.QRect(490, 320, 31, 31))
        self.pushButton_27.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_33 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_33.setGeometry(QtCore.QRect(350, 320, 31, 31))
        self.pushButton_33.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_34.setGeometry(QtCore.QRect(910, 320, 31, 31))
        self.pushButton_34.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_34.setText("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_35.setGeometry(QtCore.QRect(210, 320, 31, 31))
        self.pushButton_35.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_36.setGeometry(QtCore.QRect(770, 320, 31, 31))
        self.pushButton_36.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.label_17.raise_()
        self.label_20.raise_()
        self.textEdit_305.raise_()
        self.label_13.raise_()
        self.textEdit_302.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.lineEdit_302.raise_()
        self.textEdit_309.raise_()
        self.textEdit_301.raise_()
        self.lineEdit_301.raise_()
        self.label_21.raise_()
        self.pushButton_11.raise_()
        self.textEdit_310.raise_()
        self.textEdit_307.raise_()
        self.textEdit_311.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.textEdit_300.raise_()
        self.pushButton_301.raise_()
        self.label_24.raise_()
        self.textEdit_303.raise_()
        self.textEdit_304.raise_()
        self.textEdit_308.raise_()
        self.textEdit_306.raise_()
        self.textEdit_51.raise_()
        self.pushButton_9.raise_()
        self.pushButton_31.raise_()
        self.pushButton_27.raise_()
        self.pushButton_33.raise_()
        self.pushButton_34.raise_()
        self.pushButton_35.raise_()
        self.pushButton_36.raise_()
        self.Tag.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit_405 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_405.setGeometry(QtCore.QRect(540, 400, 41, 161))
        self.textEdit_405.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_405.setObjectName("textEdit_405")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_25.setGeometry(QtCore.QRect(910, 320, 31, 31))
        self.pushButton_25.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(210, 100, 201, 41))
        self.label_37.setObjectName("label_37")
        self.textEdit_402 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_402.setGeometry(QtCore.QRect(300, 400, 41, 161))
        self.textEdit_402.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_402.setObjectName("textEdit_402")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setGeometry(QtCore.QRect(690, 10, 191, 291))
        self.label_38.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setGeometry(QtCore.QRect(700, 20, 161, 31))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setGeometry(QtCore.QRect(200, 370, 181, 31))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(190, 10, 491, 211))
        self.label_41.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_4)
        self.label_42.setGeometry(QtCore.QRect(890, 10, 201, 291))
        self.label_42.setStyleSheet("QLabel{background-color: rgb(51, 180, 255,0.8);border-radius:15px;}\n"
"")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_4)
        self.label_43.setGeometry(QtCore.QRect(190, 230, 491, 71))
        self.label_43.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_43.setObjectName("label_43")
        self.lineEdit_402 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_402.setGeometry(QtCore.QRect(420, 110, 241, 31))
        self.lineEdit_402.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_402.setObjectName("lineEdit_402")
        self.textEdit_409 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_409.setGeometry(QtCore.QRect(860, 400, 41, 161))
        self.textEdit_409.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_409.setObjectName("textEdit_409")
        self.textEdit_401 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_401.setGeometry(QtCore.QRect(220, 400, 41, 161))
        self.textEdit_401.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_401.setObjectName("textEdit_401")
        self.label_44 = QtWidgets.QLabel(self.tab_4)
        self.label_44.setGeometry(QtCore.QRect(190, 360, 921, 211))
        self.label_44.setStyleSheet("QLabel{background:rgba(135,206,250,0.6);border-radius:15px;}")
        self.label_44.setObjectName("label_44")
        self.lineEdit_401 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_401.setGeometry(QtCore.QRect(420, 70, 241, 31))
        self.lineEdit_401.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.lineEdit_401.setText("")
        self.lineEdit_401.setObjectName("lineEdit_401")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_26.setGeometry(QtCore.QRect(490, 320, 31, 31))
        self.pushButton_26.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:15px;}\n"
"QPushButton:hover{background:green;}")
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_45 = QtWidgets.QLabel(self.tab_4)
        self.label_45.setGeometry(QtCore.QRect(900, 20, 181, 31))
        self.label_45.setObjectName("label_45")
        self.pushButton_427 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_427.setGeometry(QtCore.QRect(440, 150, 121, 41))
        self.pushButton_427.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.pushButton_427.setObjectName("pushButton_427")
        self.textEdit_410 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_410.setGeometry(QtCore.QRect(940, 400, 41, 161))
        self.textEdit_410.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_410.setObjectName("textEdit_410")
        self.textEdit_407 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_407.setGeometry(QtCore.QRect(700, 400, 41, 161))
        self.textEdit_407.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_407.setObjectName("textEdit_407")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_28.setGeometry(QtCore.QRect(630, 320, 31, 31))
        self.pushButton_28.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_28.setText("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.textEdit_411 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_411.setGeometry(QtCore.QRect(1020, 400, 41, 161))
        self.textEdit_411.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_411.setObjectName("textEdit_411")
        self.label_46 = QtWidgets.QLabel(self.tab_4)
        self.label_46.setGeometry(QtCore.QRect(210, 20, 171, 41))
        self.label_46.setObjectName("label_46")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_29.setGeometry(QtCore.QRect(350, 320, 31, 31))
        self.pushButton_29.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_47 = QtWidgets.QLabel(self.tab_4)
        self.label_47.setGeometry(QtCore.QRect(210, 60, 211, 41))
        self.label_47.setObjectName("label_47")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_30.setGeometry(QtCore.QRect(770, 320, 31, 31))
        self.pushButton_30.setStyleSheet("QPushButton{background:#F7D674;border-radius:15px;}\n"
"QPushButton:hover{background:yellow;}")
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.textEdit_400 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_400.setGeometry(QtCore.QRect(700, 50, 171, 231))
        self.textEdit_400.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_400.setObjectName("textEdit_400")
        self.pushButton_401 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_401.setGeometry(QtCore.QRect(230, 150, 121, 41))
        self.pushButton_401.setStyleSheet("QPushButton\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    border-style:outset;\n"
"    border-width:3px; \n"
"    border-color:#6495ED\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:white;\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"\n"
"}\n"
"")
        self.pushButton_401.setObjectName("pushButton_401")
        self.label_48 = QtWidgets.QLabel(self.tab_4)
        self.label_48.setGeometry(QtCore.QRect(10, 10, 131, 571))
        self.label_48.setStyleSheet("QLabel{background-color: rgb(51, 180, 255);border-radius:15px;}")
        self.label_48.setObjectName("label_48")
        self.textEdit_403 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_403.setGeometry(QtCore.QRect(380, 400, 41, 161))
        self.textEdit_403.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_403.setObjectName("textEdit_403")
        self.textEdit_404 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_404.setGeometry(QtCore.QRect(460, 400, 41, 161))
        self.textEdit_404.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_404.setObjectName("textEdit_404")
        self.textEdit_408 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_408.setGeometry(QtCore.QRect(780, 400, 41, 161))
        self.textEdit_408.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_408.setObjectName("textEdit_408")
        self.pushButton_32 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_32.setGeometry(QtCore.QRect(210, 320, 31, 31))
        self.pushButton_32.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.textEdit_406 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_406.setGeometry(QtCore.QRect(620, 400, 41, 161))
        self.textEdit_406.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_406.setObjectName("textEdit_406")
        self.textEdit_52 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_52.setGeometry(QtCore.QRect(900, 50, 181, 231))
        self.textEdit_52.setStyleSheet("background-color: rgba(255, 255, 255, 0.5)")
        self.textEdit_52.setObjectName("textEdit_52")
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(1050, 320, 31, 31))
        self.pushButton.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_44.raise_()
        self.label_41.raise_()
        self.textEdit_405.raise_()
        self.pushButton_25.raise_()
        self.label_37.raise_()
        self.textEdit_402.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.lineEdit_402.raise_()
        self.textEdit_409.raise_()
        self.textEdit_401.raise_()
        self.lineEdit_401.raise_()
        self.pushButton_26.raise_()
        self.label_45.raise_()
        self.pushButton_427.raise_()
        self.textEdit_410.raise_()
        self.textEdit_407.raise_()
        self.pushButton_28.raise_()
        self.textEdit_411.raise_()
        self.label_46.raise_()
        self.pushButton_29.raise_()
        self.label_47.raise_()
        self.pushButton_30.raise_()
        self.textEdit_400.raise_()
        self.pushButton_401.raise_()
        self.label_48.raise_()
        self.textEdit_403.raise_()
        self.textEdit_404.raise_()
        self.textEdit_408.raise_()
        self.pushButton_32.raise_()
        self.textEdit_406.raise_()
        self.textEdit_52.raise_()
        self.pushButton.raise_()
        self.Tag.addTab(self.tab_4, "")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setGeometry(QtCore.QRect(1050, 5, 41, 41))
        self.pushButton_38.setStyleSheet("QPushButton{background:#F76677;border-radius:15px;}\n"
"QPushButton:hover{background:red;}")
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        WindowMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowMain)
        self.Tag.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(self.lineEdit_101.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_102.clear)
        self.pushButton_2.clicked.connect(self.textEdit_100.clear)
        self.pushButton_2.clicked.connect(self.textEdit_1.clear)
        self.pushButton_2.clicked.connect(self.textEdit_2.clear)
        self.pushButton_2.clicked.connect(self.textEdit_3.clear)
        self.pushButton_2.clicked.connect(self.textEdit_4.clear)
        self.pushButton_2.clicked.connect(self.textEdit_5.clear)
        self.pushButton_2.clicked.connect(self.textEdit_6.clear)
        self.pushButton_2.clicked.connect(self.textEdit_7.clear)
        self.pushButton_2.clicked.connect(self.textEdit_8.clear)
        self.pushButton_2.clicked.connect(self.textEdit_9.clear)
        self.pushButton_2.clicked.connect(self.textEdit_10.clear)
        self.pushButton_2.clicked.connect(self.textEdit_11.clear)
        self.pushButton_2.clicked.connect(self.textEdit_100.clear)
        self.pushButton_19.clicked.connect(self.lineEdit_202.clear)
        self.pushButton_19.clicked.connect(self.lineEdit_201.clear)
        self.pushButton_19.clicked.connect(self.textEdit_200.clear)
        self.pushButton_19.clicked.connect(self.textEdit_201.clear)
        self.pushButton_19.clicked.connect(self.textEdit_202.clear)
        self.pushButton_19.clicked.connect(self.textEdit_203.clear)
        self.pushButton_19.clicked.connect(self.textEdit_204.clear)
        self.pushButton_19.clicked.connect(self.textEdit_205.clear)
        self.pushButton_19.clicked.connect(self.textEdit_206.clear)
        self.pushButton_19.clicked.connect(self.textEdit_207.clear)
        self.pushButton_19.clicked.connect(self.textEdit_208.clear)
        self.pushButton_19.clicked.connect(self.textEdit_209.clear)
        self.pushButton_19.clicked.connect(self.textEdit_210.clear)
        self.pushButton_19.clicked.connect(self.textEdit_211.clear)
        self.pushButton_11.clicked.connect(self.lineEdit_301.clear)
        self.pushButton_11.clicked.connect(self.textEdit_300.clear)
        self.pushButton_11.clicked.connect(self.lineEdit_302.clear)
        self.pushButton_11.clicked.connect(self.textEdit_301.clear)
        self.pushButton_11.clicked.connect(self.textEdit_302.clear)
        self.pushButton_11.clicked.connect(self.textEdit_303.clear)
        self.pushButton_11.clicked.connect(self.textEdit_304.clear)
        self.pushButton_11.clicked.connect(self.textEdit_305.clear)
        self.pushButton_11.clicked.connect(self.textEdit_306.clear)
        self.pushButton_11.clicked.connect(self.textEdit_307.clear)
        self.pushButton_11.clicked.connect(self.textEdit_308.clear)
        self.pushButton_11.clicked.connect(self.textEdit_309.clear)
        self.pushButton_11.clicked.connect(self.textEdit_310.clear)
        self.pushButton_11.clicked.connect(self.textEdit_311.clear)
        self.pushButton_427.clicked.connect(self.lineEdit_401.clear)
        self.pushButton_427.clicked.connect(self.lineEdit_402.clear)
        self.pushButton_427.clicked.connect(self.textEdit_400.clear)
        self.pushButton_427.clicked.connect(self.textEdit_401.clear)
        self.pushButton_427.clicked.connect(self.textEdit_402.clear)
        self.pushButton_427.clicked.connect(self.textEdit_403.clear)
        self.pushButton_427.clicked.connect(self.textEdit_404.clear)
        self.pushButton_427.clicked.connect(self.textEdit_405.clear)
        self.pushButton_427.clicked.connect(self.textEdit_406.clear)
        self.pushButton_427.clicked.connect(self.textEdit_407.clear)
        self.pushButton_427.clicked.connect(self.textEdit_408.clear)
        self.pushButton_427.clicked.connect(self.textEdit_409.clear)
        self.pushButton_427.clicked.connect(self.textEdit_410.clear)
        self.pushButton_427.clicked.connect(self.textEdit_411.clear)
        QtCore.QMetaObject.connectSlotsByName(WindowMain)

    def retranslateUi(self, WindowMain):
        _translate = QtCore.QCoreApplication.translate
        WindowMain.setWindowTitle(_translate("WindowMain", "MainWindow"))
        self.label_7.setText(_translate("WindowMain", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">先</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">入</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">先</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">出</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">算</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">法</span></p></body></html>"))
        self.label_8.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Control Area</span></p></body></html>"))
        self.label_3.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">预设页面号序列：</span></p></body></html>"))
        self.label_4.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">内存物理块个数：</span></p></body></html>"))
        self.pushButton_101.setText(_translate("WindowMain", "开始运行"))
        self.pushButton_2.setText(_translate("WindowMain", "清除信息"))
        self.label_5.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Message Area</span></p></body></html>"))
        self.label_10.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_12.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">FIFO Summary</span></p></body></html>"))
        self.label.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_9.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Display Area</span></p></body></html>"))
        self.textEdit_49.setHtml(_translate("WindowMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">FIFO的算法思想是总是淘汰最先进入内存的页面，即选择在内存驻留时间最长的页面予以淘汰 。其算法特点简单、易实现；貌似公平，实际上不公平，不切实际，有些经常被访问的页面可能先被淘汰，因此性能较差。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.Tag.setTabText(self.Tag.indexOf(self.tab_1), _translate("WindowMain", "FIFO"))
        self.label_25.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">内存物理块个数：</span></p></body></html>"))
        self.label_26.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_27.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Message Area</span></p></body></html>"))
        self.label_28.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Display Area</span></p></body></html>"))
        self.label_29.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_31.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_32.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_33.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">LRU Summary</span></p></body></html>"))
        self.pushButton_19.setText(_translate("WindowMain", "清除信息"))
        self.label_34.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Control Area</span></p></body></html>"))
        self.label_35.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">预设页面号序列：</span></p></body></html>"))
        self.pushButton_201.setText(_translate("WindowMain", "开始运行"))
        self.label_36.setText(_translate("WindowMain", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">最</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">近</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">最</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">久</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">未</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">使</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">用</span></p></body></html>"))
        self.textEdit_50.setHtml(_translate("WindowMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">LRU的算法思想是选择最近一段时间最久未使用的页面予以淘汰。其算法的特点是：考虑了程序设计的局部性原理，有一定合理性，但页面的过去和未来走向无必然联系；需要跟踪记录每一页的使用情况，系统开销较大。</span></p></body></html>"))
        self.Tag.setTabText(self.Tag.indexOf(self.tab_2), _translate("WindowMain", "LRU"))
        self.label_13.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">内存物理块个数：</span></p></body></html>"))
        self.label_14.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_15.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Message Area</span></p></body></html>"))
        self.label_16.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Display Area</span></p></body></html>"))
        self.label_17.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_19.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_20.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_21.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">LFU Summary</span></p></body></html>"))
        self.pushButton_11.setText(_translate("WindowMain", "清除信息"))
        self.label_22.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Control Area</span></p></body></html>"))
        self.label_23.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">预设页面号序列：</span></p></body></html>"))
        self.pushButton_301.setText(_translate("WindowMain", "开始运行"))
        self.label_24.setText(_translate("WindowMain", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">最</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">少</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">使</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">用</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">算</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">法</span></p></body></html>"))
        self.textEdit_51.setHtml(_translate("WindowMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">LFU的算法思想是与LRU类似，设置一个移位寄存器记录页面访问情况，如要置换页面，选择∑Ri值最小的页面进行淘汰。其特点是：实现比较简单但并不能真正反映页面的使用情况。</span></p></body></html>"))
        self.Tag.setTabText(self.Tag.indexOf(self.tab_3), _translate("WindowMain", "LFU"))
        self.label_37.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">内存物理块个数：</span></p></body></html>"))
        self.label_38.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_39.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Message Area</span></p></body></html>"))
        self.label_40.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Display Area</span></p></body></html>"))
        self.label_41.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_43.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_44.setText(_translate("WindowMain", "<html><head/><body><p><br/></p></body></html>"))
        self.label_45.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">CLOCK Summary</span></p></body></html>"))
        self.pushButton_427.setText(_translate("WindowMain", "清除信息"))
        self.label_46.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Control Area</span></p></body></html>"))
        self.label_47.setText(_translate("WindowMain", "<html><head/><body><p><span style=\" font-size:16pt;\">预设页面号序列：</span></p></body></html>"))
        self.pushButton_401.setText(_translate("WindowMain", "开始运行"))
        self.label_48.setText(_translate("WindowMain", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">时</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">钟</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">置</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">换</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">算</span></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">法</span></p><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\"><br/></span></p></body></html>"))
        self.textEdit_52.setHtml(_translate("WindowMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">CLOCK置换算法的算法思想是 1.为每页设置一位访问位，再将内存中所有页面链成一个循环队列。2.某页被访问时，其访问位被置1，表示该页使用过。3.置换算法在选择一页淘汰时，循环检查各页的访问位：如果为1，则将该访问位置0，暂不换出；如果为0，则将该页换出，算法终止。</span></p></body></html>"))
        self.Tag.setTabText(self.Tag.indexOf(self.tab_4), _translate("WindowMain", "CLOCK"))
